# Generated by Django 4.1.2 on 2022-10-07 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="course", old_name="user", new_name="author"),
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="students", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
