# Generated by Django 4.1.2 on 2022-10-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_rename_user_course_author_chapter_slug_course_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("input", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="textblock",
            name="slug",
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="textblock",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UserSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("time_limit", models.IntegerField(default=10)),
                ("memory_limit", models.IntegerField(default=256)),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                ("code", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                (
                    "coding_problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.codingproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
