# Generated by Django 4.1.2 on 2022-10-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_codingproblem_textblock_slug_textblock_title_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="chapter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.chapter",
            ),
        )
    ]
