# Generated by Django 4.1.2 on 2022-10-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0004_codingproblem_chapter")]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="code_template",
            field=models.TextField(blank=True),
        )
    ]
