# Generated by Django 4.1.2 on 2022-10-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0005_codingproblem_code_template")]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="output",
            field=models.TextField(blank=True),
        ),
    ]
