# Generated by Django 4.1.2 on 2022-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0006_codingproblem_deadline_codingproblem_output")]

    operations = [
        migrations.RemoveField(model_name="codingproblem", name="input"),
        migrations.RemoveField(model_name="usersolution", name="memory_limit"),
        migrations.RemoveField(model_name="usersolution", name="time_limit"),
        migrations.AddField(
            model_name="codingproblem",
            name="memory_limit",
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="time_limit",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="usersolution", name="input", field=models.TextField(blank=True)
        ),
    ]
