# Generated by Django 4.1.2 on 2022-10-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("courses", "0007_remove_codingproblem_input_and_more")]

    operations = [migrations.RemoveField(model_name="usersolution", name="code")]
