# Generated by Django 4.1.2 on 2022-11-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("courses", "0008_remove_usersolution_code")]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_question", models.TextField()),
            ],
        ),
        migrations.RemoveField(model_name="textblock", name="chapter"),
        migrations.RemoveField(model_name="chapter", name="course"),
        migrations.RemoveField(model_name="usersolution", name="coding_problem"),
        migrations.AddField(
            model_name="course",
            name="chapters",
            field=models.ManyToManyField(
                blank=True, related_name="Chapter", to="courses.chapter"
            ),
        ),
        migrations.CreateModel(
            name="CodingProblemPart",
            fields=[
                (
                    "part_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courses.part",
                    ),
                ),
                ("description", models.TextField()),
                ("time_limit", models.IntegerField(default=10)),
                ("memory_limit", models.IntegerField(default=256)),
                ("output", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("code_template", models.TextField(blank=True)),
                (
                    "user_solutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_solutions",
                        to="courses.usersolution",
                    ),
                ),
            ],
            bases=("courses.part",),
        ),
        migrations.CreateModel(
            name="QuizPart",
            fields=[
                (
                    "part_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courses.part",
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, related_name="questions", to="courses.question"
                    ),
                ),
            ],
            bases=("courses.part",),
        ),
        migrations.CreateModel(
            name="TextPart",
            fields=[
                (
                    "part_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courses.part",
                    ),
                ),
                ("content", models.TextField()),
            ],
            bases=("courses.part",),
        ),
        migrations.DeleteModel(name="CodingProblem"),
        migrations.DeleteModel(name="TextBlock"),
        migrations.AddField(
            model_name="chapter",
            name="parts",
            field=models.ManyToManyField(
                blank=True, related_name="parts", to="courses.part"
            ),
        ),
    ]
