# Generated by Django 4.1.2 on 2022-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0009_part_question_remove_textblock_chapter_and_more")]

    operations = [
        migrations.AddField(
            model_name="part",
            name="type",
            field=models.CharField(default="", max_length=100),
        )
    ]
