# Generated by Django 4.1.2 on 2022-11-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0010_part_type")]

    operations = [
        migrations.AddField(
            model_name="part", name="position", field=models.IntegerField(default=999)
        )
    ]
