# Generated by Django 4.1.2 on 2022-11-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("courses", "0011_part_position")]

    operations = [
        migrations.RemoveField(model_name="codingproblempart", name="user_solutions"),
        migrations.AddField(
            model_name="usersolution",
            name="coding_problem",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.codingproblempart",
            ),
        ),
    ]
