# Generated by Django 4.1.2 on 2022-11-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_remove_codingproblempart_user_solutions_and_more")
    ]

    operations = [
        migrations.RenameField(
            model_name="codingproblempart",
            old_name="output",
            new_name="expected_output",
        ),
        migrations.AddField(
            model_name="codingproblempart",
            name="input",
            field=models.TextField(blank=True),
        ),
    ]
